feat: replaced mathematical kwargs in scheduler constructors
FluxML/ParameterSchedulers.jl pull request #60
Opened 2024-02-13 14:08 UTC by lfenzo

Addresses #41.

For cyclic schedulers, I've replaced `λ*` with `l*`, but I'm open to suggestions. At this moment I preferred replacing only the symbols instead of making more drastic changes to the API. Tests were also adapted, but docs are still untouched, hence the "draft" status (I'll soon submit another commit tackling that).

cc.: @darsnack

2024-02-28 21:59 UTC, lfenzo commented
Good to go?

2024-02-29 14:02 UTC, darsnack requested changes
I'm happy with your chosen naming scheme, and most of the changes here are broadly good to go.

I would prefer to release a patch with deprecations first. Can we do something like this:
```
function depkwargs(fn::Symbol, kwargs, remaps::Pair...)
    remaps = Dict(remaps...)
    kwargs = map(keys(kwargs)) do kw
        if haskey(remaps, kw)
            Base.depwarn("Keyword $kw is deprecated. Replacing with $(remaps[kw]) instead.", fn)
            return remaps[kw] => kwargs[kw]
        else
            return kw => kwargs[kw]
        end
    end

    return (; kwargs...)
end

function Triangle(; kwargs...)
     kwargs = depkwargs(:Triangle, kwargs, :λ0 => :l0, :λ1 => :l1)
     return Triangle(kwargs.l0, kwargs.l1, kwargs.period)
end
```

2024-02-29 14:02 UTC, darsnack commented on docs/make.jl
> +)
It looks like your formatter is making changes that aren't necessary. Can you revert these?

2024-03-02 20:15 UTC, lfenzo commented
> `function depkwargs(fn::Symbol, kwargs, remaps::Pair...)` (..) `end`

Very clever! Added to all constructors modified in this PR. Thanks for the snippet!

2024-03-02 20:21 UTC, lfenzo commented on docs/make.jl
> +)
The "formatter" in this case is the human in front of the keyboard :laughing:. I have no problem reverting these, however I must say I prefer the new version, but that mostly concerns aesthetics.

2024-03-02 20:54 UTC, darsnack commented on docs/make.jl
> +)
I would revert them cause it just messes with the git blame

2024-03-02 21:00 UTC, darsnack requested changes
One more small change and then we are good to go. Can you also bump the patch version?

2024-03-02 21:00 UTC, darsnack commented on src/cyclic.jl
>  end
I realized that now the body of `_tridecay2` can be the positional constructor, and the keyword constructor forwards to the positional constructor. Do you mind making this change here and elsewhere?

2024-03-02 21:24 UTC, lfenzo commented on docs/make.jl
> +)
Sure!

2024-03-02 21:47 UTC, lfenzo commented on src/cyclic.jl
>  end
Done!

2024-03-02 22:06 UTC, darsnack approved these changes
Looks good, thank you! The nightly failure is unrelated to the PR.

2024-03-02 22:07 UTC, lfenzo commented
I'm still trying to figure out what happened here, as it turns out, my force push after a `git reset` to revert the formatting in `docs/make.jl` somehow caused this PR to be closed. 

The body of `_tridecay2` and its variants were transferred to the respective positional constructors; patch number was updated and CI errors with Julia nightly seem unrelated.

2024-03-02 22:14 UTC, merged